.stage_artifacts: &stage_artifacts
  artifacts:
    paths:
      - build/
      - TriBITS/
      - googletest/
      - testframework/
    expire_in: 1 day
.mingw_windows_before_script: &mingw_windows_before_script
  before_script:
    - .\ci\mingw_before_script.bat
stages:
- configure
- build
- test
- analysis

mac_clang_testing:
  tags:
    - mac
  script:
    - . ci/mac_clang_test.sh

linux_gcc_testing:
  tags:
    - linux
  script:
    - ci/linux_gcc_test.sh

linux_gcc_analysis:
  stage: analysis
  tags:
    - linux
  script:
    - ci/linux_gcc_analysis.sh
  allow_failure: true

windows_mingw_testing:
  tags:
    - mingw-gcc-4.8.5
  <<: *mingw_windows_before_script
  script:
   - where git
   - where python
   - python --version
   - where cmake
   - cmake --version
   - git clone https://github.com/lefebvre/TriBITS.git TriBITS
   - git clone https://github.com/lefebvre/testframework testframework
   - git clone https://github.com/lefebvre/googletest googletest
   - mkdir build
   - cd build
   - cmake -DBUILDNAME="Windows-MinGW-GCC-4.8.5-Debug-%CI_BUILD_REF_NAME%" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_TESTS=ON -Dwasp_ENABLE_ALL_PACKAGES=ON -G "MinGW Makefiles" ..
   - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit

windows_vs2013_testing:
  tags:
    - vs2013
  script:
    - .\ci\vs2013_test.bat

windows_intel15_testing:
  tags:
    - intel15
    - ninja
  script:
    - .\ci\windows_intel15_test.bat 

