.stage_artifacts: &stage_artifacts
  artifacts:
    paths:
      - build/
      - TriBITS/
      - googletest/
      - testframework/
    expire_in: 1 day
.windows_before_script: &windows_before_script
  before_script:
    - set PATH=%PATH%;c:\vendors\mingw-w64\x86_64-4.8.5-posix-seh-rt_v4-rev0\mingw64\bin;c:\vendors\git\2.11\cmd;c:\vendors\cmake\3.6.3\bin;
stages:
- configure
- build
- test
- analysis

configure_mac:
  stage: configure
  tags:
    - mac
  <<: *stage_artifacts
  script:
    - which git
    - git --version
    - git clone https://github.com/lefebvre/TriBITS.git TriBITS
    - git clone https://github.com/lefebvre/testframework testframework
    - git clone https://github.com/lefebvre/googletest googletest
    - which python
    - python --version
    - python TriBITS/tribits/python_utils/gitdist.py pull
    - mkdir build
    - cd build
    - module load cmake
    - which cmake
    - cmake -DBUILDNAME="$(uname -s)-AppleClang-8-Debug-${CI_BUILD_REF_NAME}" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_TESTS=ON -Dwasp_ENABLE_ALL_PACKAGES=ON ..

build_mac:
  stage: build
  tags:
    - mac
  <<: *stage_artifacts
  script:
    - cd build
    - module load cmake
    - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalSubmit
  dependencies:
    - configure_mac

test_mac:
  stage: test
  tags:
    - mac
  <<: *stage_artifacts
  script:
    - cd build
    - module load cmake
    - ctest -D ExperimentalTest -D ExperimentalSubmit
  dependencies:
    - build_mac

configure_linux:
  stage: configure
  tags:
    - linux
  <<: *stage_artifacts
  script:
    - which git
    - git --version
    - git clone https://github.com/lefebvre/TriBITS.git TriBITS
    - git clone https://github.com/lefebvre/testframework testframework
    - git clone https://github.com/lefebvre/googletest googletest
    - which python
    - python --version
    - python TriBITS/tribits/python_utils/gitdist.py pull
    - mkdir build
    - cd build
    - module load cmake
    - which cmake
    - module load valgrind
    - cmake -MEMCHECK_COMMAND="$(which valgrind)" -DBUILDNAME="$(uname -s)-GCC-4.8.5-Debug-${CI_BUILD_REF_NAME}" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_COVERAGE_TESTING=ON -D COVERAGE_EXTRA_FLAGS="-s `pwd`/../googletest -d"-Dwasp_ENABLE_TESTS=ON -Dwasp_ENABLE_ALL_PACKAGES=ON ..

build_linux:
  stage: build
  tags:
    - linux
  <<: *stage_artifacts
  script:
    - cd build
    - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalSubmit
  dependencies:
    - configure_linux

test_linux:
  stage: test
  tags:
    - linux
  <<: *stage_artifacts
  script:
    - cd build
    - ctest -D ExperimentalTest -D ExperimentalSubmit
  dependencies:
    - build_linux
analysis_linux:
  stage: analysis
  tags:
    - linux
  script:
    - cd build
    - ctest -D ExperimentalCoverage -D ExperimentalMemCheck -D ExperimentalSubmit
  dependencies:
    - test_linux
  allow_failure: true

configure_windows:
  stage: configure
  tags:
    - windows
  <<: *stage_artifacts
  <<: *windows_before_script
  script:
   - where git
   - git --version
   - where cmake
   - cmake --version
   - git clone https://github.com/lefebvre/TriBITS.git TriBITS
   - git clone https://github.com/lefebvre/testframework testframework
   - git clone https://github.com/lefebvre/googletest googletest
   - mkdir build
   - cd build
   - cmake -DBUILDNAME="Windows-MinGW-GCC-4.8.5-Debug-%CI_BUILD_REF_NAME%" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_TESTS=ON -Dwasp_ENABLE_ALL_PACKAGES=ON -G "MinGW Makefiles" ..

build_windows:
  stage: build
  tags:
    - windows
  <<: *stage_artifacts
  <<: *windows_before_script
  script:
    - cd build/
    - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalSubmit
  dependencies:
    - configure_windows

test_windows:
  stage: test
  tags:
   - windows
  <<: *stage_artifacts
  <<: *windows_before_script
  script:
    - cd build
    - ctest -D ExperimentalTest -D ExperimentalSubmit
  dependencies:
    - build_windows
