variables:
  GIT_SUBMODULE_STRATEGY: normal
.stage_artifacts: &stage_artifacts
  artifacts:
    paths:
      - build/
      - TriBITS/
      - googletest/
      - testframework/
    expire_in: 1 day
.mingw_windows_before_script: &mingw_windows_before_script
  before_script:
    - .\ci\mingw_before_script.bat
stages:
- configure
- build
- test
- analysis

mac_clang_testing:
  tags:
    - mac
  script:
    - RTN_DIR=${PWD}
    - . ci/mac_clang_test.sh python2
    - cd ${RTN_DIR} 
    - . ci/mac_clang_test.sh python3
  artifacts:
    paths:
      - "WASP*Darwin.sh"
      - waspConfig_install.cmake

doc_gen:
  tags:
    - pandoc, mac
  script:
    - which git
    - git --version
    - module load cmake
    - which cmake
    - which python
    - python --version
    - mkdir build
    - cd build
    - cmake -DBUILDNAME="$(uname -s)-DocGen-${CI_BUILD_REF_NAME}" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_ALL_PACKAGES=ON ..
    - make doc_gen
  artifacts:
    paths:
      - build/WorkbenchAnalysisSequenceProcessor.docx
      - build/WorkbenchAnalysisSequenceProcessor.pdf

linux_gcc54_testing:
  tags:
    - linux
    - gcc5.4
    - pbs
  script:
    - RTN_DIR=${PWD}
    - . ci/linux_gcc5.4_test.sh python3
    - cd ${RTN_DIR} 
    - . ci/linux_gcc5.4_test.sh python2

linux_gcc485_testing:
  tags:
    - linux
    - gcc-4.8.5
    - pbs
  script:
    - ci/linux_gcc_test.sh
  artifacts:
    paths:
      - "WASP*Linux.sh"
      - waspConfig_install.cmake

linux_gcc_analysis:
  stage: analysis
  tags:
    - linux
    - valgrind-3.11
  script:
    - ci/linux_gcc_analysis.sh
  allow_failure: true

windows_mingw_testing:
  tags:
    - mingw-gcc-4.8.5
  <<: *mingw_windows_before_script
  script:
   - .\ci\windows_mingw_test.bat

windows_vs2013_testing:
  tags:
    - vs2013
  script:
    - .\ci\vs2013_test.bat

windows_shared_vs2013_testing:
  tags:
    - vs2013
  script:
    - .\ci\vs2013_shared_test.bat

windows_intel15_testing:
  tags:
    - intel15
    - ninja
    - nsis
  script:
    - .\ci\windows_intel15_test.bat
  artifacts:
    paths:
      - "WASP*.exe"
      - waspConfig_install.cmake
