.stage_artifacts: &stage_artifacts
  artifacts:
    paths:
      - build/
      - TriBITS/
      - googletest/
      - testframework/
    expire_in: 1 day
.mingw_windows_before_script: &mingw_windows_before_script
  before_script:
    - set PATH=%PATH%;c:\vendors\mingw-w64\x86_64-4.8.5-posix-seh-rt_v4-rev0\mingw64\bin;c:\vendors\git\2.11\cmd;c:\vendors\cmake\3.6.3\bin;c:\Python27;
stages:
- configure
- build
- test
- analysis

mac_clang_testing:
  tags:
    - mac
  script:
    - which git
    - git --version
    - git clone https://github.com/lefebvre/TriBITS.git TriBITS
    - module load cmake
    - which cmake
    - which python
    - python --version
    - python TriBITS/tribits/ci_support/clone_extra_repos.py
    - mkdir build
    - cd build
    - cmake -DBUILDNAME="$(uname -s)-AppleClang-8-Debug-${CI_BUILD_REF_NAME}" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_TESTS=ON -Dwasp_ENABLE_ALL_PACKAGES=ON ..
    - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit

doc_gen:
  tags:
    - pandoc, mac
  script:
    - which git
    - git --version
    - git clone https://github.com/lefebvre/TriBITS.git TriBITS
    - module load cmake
    - which cmake
    - which python
    - python --version
    - python TriBITS/tribits/ci_support/clone_extra_repos.py
    - mkdir build
    - cd build
    - cmake -DBUILDNAME="$(uname -s)-DocGen-${CI_BUILD_REF_NAME}" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_ALL_PACKAGES=ON ..
    - make doc_gen
  artifacts:
    paths:
      - build/WorkbenchAnalysisSequenceProcessor.docx
      - build/WorkbenchAnalysisSequenceProcessor.pdf

linux_gcc_testing:
  tags:
    - linux
  script:
    - which git
    - git --version
    - git clone https://github.com/lefebvre/TriBITS.git TriBITS
    - module load cmake
    - which cmake
    - which python
    - python --version
    - python TriBITS/tribits/ci_support/clone_extra_repos.py
    - mkdir build
    - cd build
    - module load valgrind
    - cmake -DBUILDNAME="$(uname -s)-GCC-4.8.5-Release-${CI_BUILD_REF_NAME}" -DCMAKE_BUILD_TYPE=RELEASE -Dwasp_ENABLE_TESTS=ON -Dwasp_ENABLE_ALL_PACKAGES=ON ..
    - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit

linux_gcc_analysis:
  stage: analysis
  tags:
    - linux
  script:
    - which git
    - git --version
    - git clone https://github.com/lefebvre/TriBITS.git TriBITS
    - module load cmake
    - which cmake
    - which python
    - python --version
    - python TriBITS/tribits/ci_support/clone_extra_repos.py
    - mkdir build
    - cd build
    - module load valgrind
    - ls -l ${CI_PROJECT_DIR}/googletest
    - cmake -MEMCHECK_COMMAND="$(which valgrind)" -DBUILDNAME="$(uname -s)-GCC-4.8.5-Debug-${CI_BUILD_REF_NAME}" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_COVERAGE_TESTING=ON -D COVERAGE_EXTRA_FLAGS="-s ${CI_PROJECT_DIR}/googletest -d"-Dwasp_ENABLE_TESTS=ON -Dwasp_ENABLE_ALL_PACKAGES=ON ..
    - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalTest -D ExperimentalMemCheck -D ExperimentalCoverage -D ExperimentalSubmit
  allow_failure: true

windows_mingw_testing:
  tags:
    - mingw-gcc-4.8.5
  <<: *mingw_windows_before_script
  script:
   - where git
   - git --version
   - where python
   - python --version
   - where cmake
   - cmake --version
   - git clone https://github.com/lefebvre/TriBITS.git TriBITS
   - git clone https://github.com/lefebvre/testframework testframework
   - git clone https://github.com/lefebvre/googletest googletest
   - mkdir build
   - cd build
   - cmake -DBUILDNAME="Windows-MinGW-GCC-4.8.5-Debug-%CI_BUILD_REF_NAME%" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_TESTS=ON -Dwasp_ENABLE_ALL_PACKAGES=ON -G "MinGW Makefiles" ..
   - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit

windows_vs2013_testing:
  tags:
    - vs2013
  script:
    - where git
    - git --version
    - where python
    - python --version
    - where cmake
    - cmake --version
    - git clone https://github.com/lefebvre/TriBITS.git TriBITS
    - git clone https://github.com/lefebvre/testframework testframework
    - git clone https://github.com/lefebvre/googletest googletest
    - mkdir build
    - cd build
    - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
    - cmake -DBUILDNAME="Windows-CL-18-Release-%CI_BUILD_REF_NAME%" -DCMAKE_BUILD_TYPE:STRING=RELEASE -Dwasp_ENABLE_TESTS:BOOL=ON -Dwasp_ENABLE_ALL_PACKAGES:BOOL=ON -G "Visual Studio 12 2013 Win64" ..
    - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit

windows_intel15_testing:
  tags:
    - intel15
    - ninja
  script:
    - where git
    - git --version
    - where python
    - python --version
    - set PATH=c:\vendors\cmake-ninja\bin;%PATH%
    - where cmake
    - cmake --version
    - git clone https://github.com/lefebvre/TriBITS.git TriBITS
    - git clone https://github.com/lefebvre/testframework testframework
    - git clone https://github.com/lefebvre/googletest googletest
    - mkdir build
    - cd build
    - call "C:\Program Files (x86)\Intel\Composer XE 2015\bin\ipsxe-comp-vars.bat" intel64 vs2013
    - cmake -DCMAKE_C_COMPILER=icl -D CMAKE_CXX_COMPILER=icl -DBUILDNAME="Windows-Intel-15.0-Release-%CI_BUILD_REF_NAME%" -DCMAKE_BUILD_TYPE:STRING=RELEASE -Dwasp_ENABLE_TESTS:BOOL=ON -Dwasp_ENABLE_ALL_PACKAGES:BOOL=ON -G "Ninja" ..
    - ctest -D ExperimentalStart -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit

