.stage_artifacts: &stage_artifacts
  artifacts:
    paths:
      - build/
      - TriBITS/
      - googletest/
      - testframework/
    expire_in: 1 day
.mingw_windows_before_script: &mingw_windows_before_script
  before_script:
    - .\ci\mingw_before_script.bat
stages:
- configure
- build
- test
- analysis

mac_clang_testing:
  tags:
    - mac
  script:
    - . ci/mac_clang_test.sh

linux_gcc_testing:
  tags:
    - linux
  script:
    - ci/linux_gcc_test.sh

linux_gcc_analysis:
  stage: analysis
  tags:
    - linux
  script:
    - ci/linux_gcc_analysis.sh
  allow_failure: true

windows_mingw_testing:
  tags:
    - mingw-gcc-4.8.5
  <<: *mingw_windows_before_script
  script:
   - .\ci\windows_mingw_test.bat

windows_vs2013_testing:
  tags:
    - vs2013
  script:
    - .\ci\vs2013_test.bat

windows_intel15_testing:
  tags:
    - intel15
    - ninja
  script:
    - .\ci\windows_intel15_test.bat 

